name: ensan_7ayawan_shay2
description: "Human, Animal, Thing multiplayer word game"
publish_to: 'none'
version: 0.1.0+1

environment:
  sdk: ^3.11.3

dependencies:
  cached_network_image: ^3.4.1
  cloud_firestore: ^6.10.0
  firebase_auth: ^6.7.0
  firebase_core: ^4.15.0
  firebase_database: ^12.6.0
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.6.1
  go_router: ^17.5.0
  google_fonts: ^6.2.1
  shared_preferences: ^2.5.5
  url_launcher: ^6.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/logo.png
    - assets/images/google_logo.png
